### PR TITLE
add lint-gci

### PR DESCRIPTION
**Pull request by zirain**
I test this in local, both `make gen`  and `make lint` passed.
if https://github.com/istio/istio/pull/40056 merged, we can merge this.

cc @howardjohn @ericvn 

istio/istio https://github.com/istio/istio/pull/40056
istio/proxy https://github.com/istio/proxy/pull/3960
istio/tools https://github.com/istio/tools/pull/2073
istio/release-builder NONE

### CODE REVIEW

**Comment by zirain** [comment]
still got issue with `pilot/pkg/config/kube/crdclient/cache_handler.go:20:1: Expected '\t', Found '\n' at pilot/pkg/config/kube/crdclient/cache_handler.go[line 20,col 1] (gci)`

```golang
	"k8s.io/client-go/informers"

	// import GKE cluster authentication plugin
	_ "k8s.io/client-go/plugin/pkg/client/auth/gcp"
	// import OIDC cluster authentication plugin, e.g. for Tectonic
	_ "k8s.io/client-go/plugin/pkg/client/auth/oidc"
	"k8s.io/client-go/tools/cache"
	gatewayapiclient "sigs.k8s.io/gateway-api/pkg/client/clientset/versioned"

	istioclient "istio.io/client-go/pkg/clientset/versioned"
```

**Comment by ericvn** [comment]
ou might review https://github.com/istio/common-files/pull/608

**Comment by zirain** [comment]
> You might review #608

yes, I'm looking for a way to make them work together.

**Review by howardjohn — COMMENTED** [review]
can you add to .golangci-format.yml as well? see https://github.com/istio/istio/pull/40047

**Comment by zirain** [comment]
> can you add to .golangci-format.yml as well? see [istio/istio#40047](https://github.com/istio/istio/pull/40047)

I will test it today

**Comment by daixiang0** [comment]
> still got issue with `pilot/pkg/config/kube/crdclient/cache_handler.go:20:1: Expected '\t', Found '\n' at pilot/pkg/config/kube/crdclient/cache_handler.go[line 20,col 1] (gci)`
> 
> ```go
> 	"k8s.io/client-go/informers"
> 
> 	// import GKE cluster authentication plugin
> 	_ "k8s.io/client-go/plugin/pkg/client/auth/gcp"
> 	// import OIDC cluster authentication plugin, e.g. for Tectonic
> 	_ "k8s.io/client-go/plugin/pkg/client/auth/oidc"
> 	"k8s.io/client-go/tools/cache"
> 	gatewayapiclient "sigs.k8s.io/gateway-api/pkg/client/clientset/versioned"
> 
> 	istioclient "istio.io/client-go/pkg/clientset/versioned"
> ```

Refer to https://github.com/daixiang0/gci/issues/76#issuecomment-1186911541

You can put comment after import.

**Comment by zirain** [comment]
> can you add to .golangci-format.yml as well? see [istio/istio#40047](https://github.com/istio/istio/pull/40047)

seems add that will broken `make gen`

**Review by ericvn — APPROVED** [review]
PRs exist for changes in other repos for this change.

**Pull request merged**
