### PR TITLE
Bump metallb

### PR DESCRIPTION
**Pull request by jwendell**

### CODE REVIEW

**Comment by jwendell** [comment]
Needs https://github.com/istio/istio/pull/48012
Nothing breaks: https://github.com/istio/istio/pull/48010

**Comment by jwendell** [comment]
@howardjohn I can replace quay with gcr, these two images need to be mirrored:
- quay.io/metallb/controller:v0.13.12
- quay.io/metallb/speaker:v0.13.12

**Comment by zirain** [comment]
> @howardjohn I can replace quay with gcr, these two images need to be mirrored:
> 
> * quay.io/metallb/controller:v0.13.12
> * quay.io/metallb/speaker:v0.13.12

should we have a pipeline for this instead of manually?

**Review by howardjohn — COMMENTED** [review]
I upload the images to GCR, will approve once PR uses them. Thanks!

**Comment by jwendell** [comment]
@howardjohn done. Note that istio needs https://github.com/istio/istio/pull/48012 - The new metallb installs a webhook and that uncovered a logic error in one test.

**Review by howardjohn — APPROVED** [review]

**Comment by ericvn** [comment]
@jwendell Looks like this is also causing failures in istio.io tests as there seems to be a metallb webhook...

**Pull request merged**
