### PR TITLE
We trust in quay.io registry

### PR DESCRIPTION
**Pull request by jwendell**

### CODE REVIEW

**Comment by howardjohn** [comment]
Where do we plan to use it? I don't personally trust quay for reliability - it caused plenty of issues when we had critical images there. So would not be in favor of having any core images there, but for other uses could be ok

**Comment by jwendell** [comment]
I see. Maistra does use quay (for instance to use centos stream images), so I thought it'd be ok to whitelist it.

**Review by howardjohn — APPROVED** [review]
whitelist for linter sgtm. Just would prefer. not to use this in our core images

**Pull request merged**
