### PR TITLE
Move tracing script over

### PR DESCRIPTION
**Pull request by howardjohn**
This includes https://github.com/istio/istio/pull/46191/files

### CODE REVIEW

**Comment by ericvn** [comment]
LGTM. Would like to verify my other PR does indeed solve the postsumit issue.

**Comment by ericvn** [comment]
OK. Looks like https://github.com/istio/istio/pull/46195 finally got postsubmits working.

**Comment by howardjohn** [comment]
Thanks @ericvn - synced now

**Comment by howardjohn** [comment]
Actually let me test end to end in istio (actually reporting traces)

**Review by ericvn — APPROVED** [review]
Approved. Feel free to remove the DNM after testing.

**Pull request merged**
